### ISSUE TITLE
about rstr 

### ISSUE THREAD

**Issue by zfxxfeng** [CcphAmy/NetEaseCloudMusic-nonmembership-list-download#7]
rstr = r"[\/\\\:\*\?\"\<\>\|]"  # '/ \ : * ? " < > |'
		for x in values:
			x['name'] = re.sub(rstr, "_", x['name'])
您好，请问呢x['name'] = re.sub(rstr, "_", x['name'])这个操作的目的是什么呢？期待您的回答，谢谢

**Comment by CcphAmy** [comment]
过滤掉一些特殊字符，以防止不能命名
